### PR TITLE
Prevent rogue apostrophes from causing mayhem.

### PR DESCRIPTION
**Pull request by 4gra**
A message or display name containing a single-quote character would produce unpredictable results at best.  I'm sure there's probably some better escaping mechanism but here's a really trivial solution in the meantime.

### CODE REVIEW

**Comment by danielb2** [comment]
I'm not sure how I missed this pull request. Trying to merge it now, but getting some odd errors in github. Will try again.

**Comment by 4gra** [comment]
Weird - I didn't get notified of your comment, either.  I think github must just hate this pull request.  it doesn't look like you've succeeded yet so good luck!

**Comment by danielb2** [comment]
still getting the error " Something went wrong with that request. Please try again."

I suppose I can try pulling from your repo manually to merge it. I'll make myself a reminder this time and try later.

**Comment by 4gra** [comment]
Yes... it's not exactly patch of the century(!)  Thanks again.

**Comment by danielb2** [comment]
I just did a manual pull from your gitrepo. Worked fine. Dunno what github's problem was with that. 

Anyway, thanks for the patch!

**Pull request merged**
